### ISSUE TITLE
Thank you for your excellent work. Is the website www.jailbreakchat.com inaccessible now?

### ISSUE THREAD

**Issue by xlnn** [xijia-tao/ImgTrojan#2]
Hello. Thank you for your excellent work. Is the website www.jailbreakchat.com inaccessible now? Is there any way to obtain the data inside? Thank you!

**Comment by Harry-Sheng** [comment]
https://github.com/alexalbertt/jailbreakchat

**Comment by xijia-tao** [comment]
Hi there! Thank you for your question. Since it has been resolved, I will close this issue.
